### ISSUE TITLE
Permanent link

### ISSUE THREAD

**Issue by chad-upton** [vincentbernat/dashkiosk#23] opened 2015-06-09 20:28 UTC
We are trying to setup some raspberry pi's to automatically reload the group they were in if they are rebooted.

We tried bookmarking and setting the homepage to the registr url that it receives the first time it checks in, but we've had instances where it generates a new display.

Is there a way to pass a parameter or to set it so the links are always going to the same display even if the cookies are deleted?

**Comment by vincentbernat** [comment] 2015-06-09 21:10
❦  9 juin 2015 13:28 -0700, Chad Upton <notifications@github.com> :

> We tried bookmarking and setting the homepage to the registr url that
> it receives the first time it checks in, but we've had instances where
> it generates a new display.

Using this URL should work as you expect. What browser are you using on
the Pi?
-- 
Write clearly - don't sacrifice clarity for "efficiency".
            - The Elements of Programming Style (Kernighan & Plauger)

**Comment by chad-upton** [comment] 2015-06-09 21:12
Chromium.

I've also noticed this behavior just using Chrome on my mac.  Not sure what exactly causes it but reconnecting an existing tab using the same url has given me a different display in the admin.

However it doesn't do it every time which is why it's hard to track down.

**Comment by vincentbernat** [comment] 2015-06-09 21:24
❦  9 juin 2015 14:12 -0700, Chad Upton <notifications@github.com> :

> I've also noticed this behavior just using Chrome on my mac. Not sure
> what exactly causes it but reconnecting an existing tab using the same
> url has given me a different display in the admin.
>
> However it doesn't do it every time which is why it's hard to track
> down.

I'll check how this could happen.
-- 
Test input for validity and plausibility.
            - The Elements of Programming Style (Kernighan & Plauger)

**Comment by chad-upton** [comment] 2015-06-09 21:26
That would be great, this app has become a central part of a project we are trying to roll out and it's working great outside of this little issue.

We are pairing with nightwatch.js/selenium to login to some private dashboards, take screenshots, then provide them to dashkiosk via nginx.  Working really well.

**Comment by vincentbernat** [comment] 2015-06-10 05:42
I don't see anything wrong in the code and I am unable to reproduce it on my side. If you can easily reproduce it with a browser, could you try applying this patch:

```diff
diff --git a/lib/api/socketio/displays.js b/lib/api/socketio/displays.js
index c933c7882139..f13f9d6debdb 100644
--- a/lib/api/socketio/displays.js
+++ b/lib/api/socketio/displays.js
@@ -16,12 +16,14 @@ function handleNewDisplay(io) {
     socket.on('register', function(data, fn) {
 
       // Handle registration, retrieve the display name or generate a new one.
+      logger.info('client registering with data', data);
       var name;
       try {
         name = JSON.parse(scs.decode(data.blob)).name;
       } catch (e) {
         name = null;
       }
+      logger.info('client registering with name', name);
 
       // Find the display
       models.Display.register(name)
```

And when a client fails to register to its old name, check what is being said for the two added log lines.

**Comment by chad-upton** [comment] 2015-06-10 19:39
I think I figured it out.  We were passing --icognito to chromium on our raspberry pi's and that was causing it.

Have another issue with grunt failing on socket.io that I can open another issue if you would like or post it here.

**Comment by vincentbernat** [comment] 2015-06-10 22:43
❦ 10 juin 2015 12:39 -0700, Chad Upton <notifications@github.com> :

> I think I figured it out. We were passing --icognito to chromium on
> our raspberry pi's and that was causing it.

It should still work fine with the URL token (only the cookie/local
storage token would be cleared). The way it works is that a token is
generated and stored in the URL, in a cookie and in local storage. If
you give back the URL with the token to the raspberry, it should work
even in incognito mode.

But if it works now, no need to investigate if you don't have time for
it.

> Have another issue with grunt failing on socket.io that I can open
> another issue if you would like or post it here.

Yes, please, open another issue. I think this may be a bower problem and
will try to use browserify instead, but let's discuss that in a proper
issue.
-- 
Avoid unnecessary branches.
            - The Elements of Programming Style (Kernighan & Plauger)

**Comment by vincentbernat** [comment] 2015-08-04 09:38
Closing this issue. Reopen in case it happens again.

**Closed by vincentbernat** 2015-08-04 09:38 UTC
