### ISSUE TITLE
Server Installation (Raspberry PI) Issue

### ISSUE THREAD

**Issue by npanayiotou** [vincentbernat/dashkiosk#44] opened 2016-07-11 08:38 UTC
I get this error when ever i try to run the server. Any suggestions?

![screenshot 2016-07-11 09 36 18](https://cloud.githubusercontent.com/assets/6696035/16724545/299be238-474b-11e6-82b5-8617d6b829e1.png)

**Comment by vincentbernat** [comment] 2016-07-11 09:22
Try `npm install sqlite3@"~3.1.0"`. You are likely to get an error.

**Comment by npanayiotou** [comment] 2016-07-11 09:48
Hi @vincentbernat, thank you for your reply. I tried that and got this - 
![screenshot 2016-07-11 10 47 32](https://cloud.githubusercontent.com/assets/6696035/16726594/f6dabaae-4754-11e6-9ada-30b87ec12dc7.png)

**Comment by vincentbernat** [comment] 2016-07-11 11:12
The output is incomplete. It misses the last lines.

**Comment by npanayiotou** [comment] 2016-07-11 11:18
pi@raspberrypi:~/Downloads/dashkiosk-2.6.6/dist $ npm install sqlite3@"~3.1.0"
-
> sqlite3@3.1.4 install /home/pi/Downloads/dashkiosk-2.6.6/dist/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v46-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.4 and node@4.4.7 (node-v46 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/home/pi/Downloads/dashkiosk-2.6.6/dist/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3090100/sqlite3.o
  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginOpen(node_sqlite3::Database::Baton*)’:
../src/database.cc:143:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginClose(node_sqlite3::Database::Baton*)’:
../src/database.cc:227:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginExec(node_sqlite3::Database::Baton*)’:
../src/database.cc:505:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginLoadExtension(node_sqlite3::Database::Baton*)’:
../src/database.cc:605:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
  CXX(target) Release/obj.target/node_sqlite3/src/node_sqlite3.o
  CXX(target) Release/obj.target/node_sqlite3/src/statement.o
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginPrepare(node_sqlite3::Database::Baton*)’:
../src/statement.cc:118:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
In file included from ../src/statement.cc:6:0:
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginBind(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:322:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Bind);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginGet(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:370:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Get);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginRun(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:438:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Run);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginAll(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:504:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(All);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginEach(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:601:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Each);
     ^
../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginReset(node_sqlite3::Statement::Baton*)’:
../src/macros.h:125:9: warning: unused variable ‘status’ [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),                              \
         ^
../src/statement.cc:724:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Reset);
     ^
  SOLINK_MODULE(target) Release/obj.target/node_sqlite3.node
  COPY Release/node_sqlite3.node
  COPY /home/pi/Downloads/dashkiosk-2.6.6/dist/node_modules/sqlite3/lib/binding/node-v46-linux-arm/node_sqlite3.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/home/pi/Downloads/dashkiosk-2.6.6/dist/node_modules/sqlite3/build'
sqlite3@3.1.4 node_modules/sqlite3
└── nan@2.3.5
pi@raspberrypi:~/Downloads/dashkiosk-2.6.6/dist $

**Comment by vincentbernat** [comment] 2016-07-11 11:30
So, it worked. I think that the original error should now be gone.

**Comment by npanayiotou** [comment] 2016-07-11 12:07
Unfortunately i am still getting the same error :/ any other suggestions @vincentbernat ?

**Comment by vincentbernat** [comment] 2016-07-11 12:14
Try create `dist/db` directory.

**Comment by npanayiotou** [comment] 2016-07-11 12:17
it already exist

**Comment by npanayiotou** [comment] 2016-07-11 12:27
![screenshot 2016-07-11 13 26 54](https://cloud.githubusercontent.com/assets/6696035/16730497/2cb887d0-476b-11e6-86a1-21323f9a0d66.png)

**Comment by vincentbernat** [comment] 2016-07-11 12:40
What's the output of `ls -ld dist/db dist/db/*`?

**Comment by npanayiotou** [comment] 2016-07-11 12:42
![screenshot 2016-07-11 13 42 07](https://cloud.githubusercontent.com/assets/6696035/16730909/583bd388-476d-11e6-8505-6aac215c6ac4.png)

**Comment by npanayiotou** [comment] 2016-07-11 12:44
![screenshot 2016-07-11 13 43 54](https://cloud.githubusercontent.com/assets/6696035/16730947/87dd738a-476d-11e6-8b4a-ed8fe5de6ba2.png)

**Comment by vincentbernat** [comment] 2016-07-11 12:53
The files are owned by root. You did a part of the installation as root. Either redo as `pi` or run the server as `root`.

**Comment by npanayiotou** [comment] 2016-07-11 13:02
Ok that seemed to work! Thank you @vincentbernat! One more thing, if i try http://localhost:9400/admin i get this. 

![screenshot 2016-07-11 14 01 59](https://cloud.githubusercontent.com/assets/6696035/16731449/0d7aa7e0-4770-11e6-8ce6-6a459e519f7c.png)

**Comment by npanayiotou** [comment] 2016-07-11 13:13
Might need to reinstall everything under @root?

**Comment by vincentbernat** [comment] 2016-07-11 13:39
Do you have `dist/public/admin.html`?

**Comment by npanayiotou** [comment] 2016-07-11 14:00
yeah its there

**Comment by vincentbernat** [comment] 2016-07-11 14:08
Just to be sure, maybe you can start again the install procedure from a fresh directory? You don't need to do anything as root.

**Comment by npanayiotou** [comment] 2016-07-11 14:14
yeah i'll do the whole thing again and keep you posted. Thank you very much for all your help @vincentbernat !

**Comment by npanayiotou** [comment] 2016-07-12 08:04
Hello @vincentbernat, so i tried a fresh installation yesterday and i got this error when i executed grunt - 
![screenshot 2016-07-12 09 03 42](https://cloud.githubusercontent.com/assets/6696035/16759569/8b52f7ea-480f-11e6-9d2b-70edebcb99c5.png)

**Comment by vincentbernat** [comment] 2016-07-12 08:41
I think this would go away if you use `sudo apt-get install libjpeg-progs`.

**Comment by npanayiotou** [comment] 2016-07-12 08:49
Nop that didnt work.

**Comment by vincentbernat** [comment] 2016-07-12 09:13
Does the file before `ENOENT` exists? If yes, what the command `file .../vendor/jpegtran` says?

**Comment by npanayiotou** [comment] 2016-07-12 09:19
Weird, i tried it again an now i am getting different errors. 
![screenshot 2016-07-12 10 19 36](https://cloud.githubusercontent.com/assets/6696035/16761898/28678b22-481a-11e6-87f6-34feb8fa1f7a.png)

**Comment by vincentbernat** [comment] 2016-07-12 09:30
In `Gruntfile.js`, remove the line with `test` at the very end (in `grunt.registarTask('dist')` block)

**Comment by vincentbernat** [comment] 2016-07-12 09:30
But you will get the same error as originally.

**Comment by npanayiotou** [comment] 2016-07-12 10:22
ok i removed that line but now im getting the original error as you said. 
tried --force but i get a bunch of other errors.

**Comment by vincentbernat** [comment] 2016-07-12 11:46
No way this will work with `--force`. I don't know why this is worst than you tried the first time. You may have changed something?

**Comment by npanayiotou** [comment] 2016-07-12 12:10
No i haven't, i was getting some warnings the first time i did it but used --force and it worked...this is weird

**Comment by npanayiotou** [comment] 2016-07-12 12:40
What OS do you recommend using this? Maybe im getting these issues because im using 
RASPBIAN JESSIE?

**Comment by vincentbernat** [comment] 2016-07-12 12:53
The `--force` may explain why you didn't get the admin page. You just skip parts of the install process that were needed. I don't think the problem is Raspbian Jessie, but the JS ecosystem may not support ARM correctly. Do the `file` stuff I said previously.

**Comment by npanayiotou** [comment] 2016-07-12 14:06
Ok so i just checked and /vendor doesn't exist.

**Comment by npanayiotou** [comment] 2016-07-14 09:23
So i re-installed everything on a laptop but now im getting "error: uncaughtException: Uncaught, unspecified "error" event. (Failed to find SQL server. Please double check your settings) when i execute "node server.js --environment production".

**Comment by vincentbernat** [comment] 2016-07-14 09:31
It seems to be the original error you got at the beginning. Post the whole trace.

**Comment by npanayiotou** [comment] 2016-07-14 09:37
nick@nick:~/dashkiosk/dashkiosk-2.6.6/dist$ node server.js --environment production
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
error: uncaughtException: Uncaught, unspecified "error" event. (Failed to find SQL server. Please double check your settings.) 
{ date: 'Thu Jul 14 2016 10:19:49 GMT+0100 (BST)',
  process: 
   { pid: 5464,
     uid: 1000,
     gid: 1000,
     cwd: '/home/nick/dashkiosk/dashkiosk-2.6.6/dist',
     execPath: '/usr/local/bin/node',
     version: 'v4.4.7',
     argv: 
      [ '/usr/local/bin/node',
        '/home/nick/dashkiosk/dashkiosk-2.6.6/dist/server.js',
        '--environment',
        'production' ],
     memoryUsage: { rss: 86360064, heapTotal: 62326896, heapUsed: 34460752 } },
  os: 
   { loadavg: [ 0.080078125, 0.18798828125, 0.43212890625 ],
     uptime: 4001 },
  trace: 
   [ { column: 17,
       file: 'events.js',
       function: 'EventEmitter.emit',
       line: 144,
       method: 'emit',
       native: false },
     { column: 19,
       file: '/home/nick/dashkiosk/dashkiosk-2.6.6/node_modules/sequelize/lib/dialects/sqlite/connector-manager.js',
       function: '',
       line: 27,
       method: null,
       native: false } ],
  stack: 
   [ 'Error: Uncaught, unspecified "error" event. (Failed to find SQL server. Please double check your settings.)',
     '    at EventEmitter.emit (events.js:144:17)',
     '    at Database.<anonymous> (/home/nick/dashkiosk/dashkiosk-2.6.6/node_modules/sequelize/lib/dialects/sqlite/connector-manager.js:27:19)' ] }

**Comment by vincentbernat** [comment] 2016-07-14 09:44
OK, so it's the same error as initially. I don't know why the message is not more helpful, but it's an access problem. What's the output of `ls -ld db db/*`?

**Comment by npanayiotou** [comment] 2016-07-14 09:46
nick@nick:~/dashkiosk/dashkiosk-2.6.6/dist$ ls -ld db db/*
drwxr-xr-x 3 root root 4096 Jul 14 10:09 db
drwxr-xr-x 2 root root 4096 Jul 14 10:09 db/migrations

**Comment by vincentbernat** [comment] 2016-07-14 09:47
Use `sudo chown -R nick:nick .` to fix permissions. Some steps have been executed by root.

**Comment by npanayiotou** [comment] 2016-07-14 10:53
awesome that worked! thank you @vincentbernat! got another issue now :P So i have the server up and running and created a group with some dashboard but when i point my client to /receiver i only get a white page, it doesnt show the dashboard. any ideas?

**Comment by npanayiotou** [comment] 2016-07-14 11:02
nevermind made it work :) thanks again @vincentbernat

**Comment by vincentbernat** [comment] 2016-07-14 11:06
For white pages, there are some hints in the documentation: http://dashkiosk.readthedocs.io/en/latest/usage.html#iframes

**Comment by npanayiotou** [comment] 2016-07-14 17:15
So i have a bunch or raspberry pi's around the office connected to TV's. They turn on automatically at 9am and i've set them up to open a browser in kiosk mode and navigate to /receiver. My question is, is there a way to save the screens in the admin panel? Every time the Pi's restart they automatically appear back in the unassigned section so i have to manually drag them to their group again.

**Comment by npanayiotou** [comment] 2016-07-14 17:19
Actually if i dont touch the admin panel they stay in their group. ignore me :)

**Comment by plitewaikato** [comment] 2016-07-14 21:00
This is a good idea, I'm currently setting up my pi zero to be my new
dashkiosk server.  I'll keep you posted and load an image file somewhere if
I get her running.

**Comment by npanayiotou** [comment] 2016-07-15 13:57
@plitewaikato yeah let know how that works out for you

**Comment by vincentbernat** [comment] 2016-07-17 05:41
The original bug seemed to be a permission problem. Closing this issue.

**Closed by vincentbernat** 2016-07-17 05:41 UTC
